import Head from 'next/head';
import React from 'react';
import { Menu } from './Menu';

export const Layout = ({ children }: any) => {
    return (
        <>
            <Head>
                <title>Fixture App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600;700&display=swap" rel="stylesheet"></link>
            </Head>
            <main>
                <Menu />
                {children}
            </main>
        </>
    )
}
