import Head from 'next/head';
import React from 'react';
import { Menu } from './Menu';

export const Layout = ({ children }: any) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Menu/>
                {children}
            </main>
            <footer>

            </footer>
        </>
    )
}
